name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Start application and test
      run: |
        # Запускаем приложение в фоне
        java -jar ./artifacts/app-card-delivery.jar &
        APP_PID=$!
        
        # Ждем 10 секунд чтобы приложение запустилось
        sleep 10
        
        # Запускаем тесты
        ./gradlew test --info -Dselenide.headless=true
        
        # Останавливаем приложение
        kill $APP_PID 2>/dev/null || true